import pool from './sketchPool.json'
import type { Shop } from './types'

/** Hand-written-style sketches of how F&B customers move between shops. Shown on the Ask page when
 *  the simulation cannot answer; clearly labelled as illustrative, never as a simulated result.
 *  The pool itself is generated by tools/gen_sketches.py (lever x segment x variant). */
export interface MockAnswer {
  headline: string
  movements: string[]
  drivers: string[]
  net: string
}

export interface SketchSetup {
  focus: string
  shops: Record<string, Shop>
}

export interface Picked {
  mock: MockAnswer
  /** 0..1 — how much of the sketch's topic, direction, audience and set-up the plan touched. */
  relevance: number
  /** How many of the shortlisted sketches cleared the relevance bar. */
  shortlisted: number
  poolSize: number
}

interface RawSketch extends MockAnswer {
  lever: string
  segment: string
}

const SKETCHES = pool.sketches as RawSketch[]
const LEVERS = pool.levers as Record<string, { tags: string[]; setup: string[] }>
const SEGMENTS = pool.segments as Record<string, string[]>

export const POOL_SIZE = SKETCHES.length
export const SHORTLIST = 40
export const RELEVANCE_BAR = 0.7

const W = { topic: 0.5, detail: 0.2, audience: 0.15, setup: 0.15 }

const SEEN_KEY = 'simffee.seenSketches'

const seen = (): number[] => {
  try {
    const raw = JSON.parse(sessionStorage.getItem(SEEN_KEY) ?? '[]') as unknown
    return Array.isArray(raw) ? raw.filter((n): n is number => Number.isInteger(n) && n >= 0 && n < POOL_SIZE) : []
  } catch {
    return []
  }
}

const remember = (used: number[]) => {
  try {
    sessionStorage.setItem(SEEN_KEY, JSON.stringify(used))
  } catch {
    // storage unavailable: still return a sketch, just without memory
  }
}

const singular = (w: string) => (w.length > 3 && w.endsWith('s') ? w.slice(0, -1) : w)

/** "open at 6", "close at 9pm", "opening 10:30" -> minutes since midnight, or null. Bare hours 1-6
 *  after "close" are read as afternoon. */
function requestedTime(lower: string, verb: 'open' | 'clos'): number | null {
  const m = new RegExp(`\\b(?:re)?${verb}\\w*\\s+(?:at\\s+|until\\s+|till\\s+)?(\\d{1,2})(?::(\\d{2}))?\\s*(am|pm)?\\b`).exec(lower)
  if (!m) return null
  let h = Number(m[1])
  const minutes = Number(m[2] ?? 0)
  if (minutes > 59) return null
  if (m[3]) {
    if (h < 1 || h > 12) return null
    if (h === 12) h = 0
    if (m[3] === 'pm') h += 12
  } else {
    if (h > 23) return null
    if (verb === 'clos' && h <= 6) h += 12
  }
  return h * 60 + minutes
}

/** Whole-word match of a shop name inside the plan ("Bean" must not match "beans"). */
const namedIn = (lower: string, name: string) => {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return new RegExp(`(^|[^a-z0-9])${escaped}(?![a-z0-9])`).test(lower)
}

const clock = (hhmm: string | undefined): number | null => {
  const m = /^(\d{1,2}):(\d{2})$/.exec(hhmm ?? '')
  return m ? Number(m[1]) * 60 + Number(m[2]) : null
}

interface Features {
  f: Set<string>
  /** Id of the non-focus shop the plan names, if any. */
  rival: string | null
}

/** Words and short phrases the plan and the set-up put on the table. Opening/closing direction is
 *  judged against the focus shop's current hours when a set-up is loaded, else against typical hours. */
function features(text: string, setup: SketchSetup | null): Features {
  const lower = text.toLowerCase()
  const words = lower.split(/[^a-z0-9-]+/).filter(Boolean)
  const f = new Set<string>()
  for (const w of words) {
    f.add(w)
    f.add(singular(w))
  }
  if (/\b\d+\s*k\b|\bprice|\bcost|\bcharge|\bvnd\b|\$/.test(lower)) f.add('price')
  if (/\b\d{1,2}\s*(am|pm)\b|\bat\s+\d{1,2}\b|\b(re)?open|\b(re)?clos|\bhour/.test(lower)) f.add('hours')
  if (/\b(re)?open/.test(lower)) f.add('opening')
  if (/\b(re)?clos/.test(lower)) f.add('closing')
  const focus = setup?.shops[setup.focus]
  const wantOpen = requestedTime(lower, 'open')
  const wantClose = requestedTime(lower, 'clos')
  const nowOpen = clock(focus?.open) ?? 7 * 60
  const nowClose = clock(focus?.close) ?? 18 * 60
  if (wantOpen != null && wantOpen !== nowOpen) f.add(wantOpen < nowOpen ? 'earlier' : 'later')
  if (wantClose != null && wantClose !== nowClose) f.add(wantClose < nowClose ? 'earlier' : 'later')
  if (!setup) return { f, rival: null }
  // Named rival: the longest full-name match wins; a distinctive word of a name only counts
  // when it does not point at more than one shop.
  let rival: string | null = null
  let rivalLen = 0
  const partial: string[] = []
  for (const [id, shop] of Object.entries(setup.shops)) {
    const name = shop.name.toLowerCase()
    if (id !== setup.focus) {
      if (namedIn(lower, name)) {
        if (name.length > rivalLen) [rival, rivalLen] = [id, name.length]
      } else if (name.split(/\s+/).some((part) => part.length > 3 && f.has(part))) {
        partial.push(id)
      }
    }
    for (const p of shop.products) if (lower.includes(p.toLowerCase())) f.add('product')
  }
  if (!rival && partial.length === 1) rival = partial[0]
  if (rival || partial.length) {
    f.add('competitor')
    f.add('rival')
  }
  if (focus && Object.keys(focus.price).some((p) => lower.includes(p.toLowerCase()))) f.add('price')
  return { f, rival }
}

const hit = (tag: string, f: Set<string>, lower: string) =>
  tag.includes(' ') || tag.includes('-') ? lower.includes(tag) : f.has(tag) || f.has(singular(tag))

function setupSatisfied(needs: string[], setup: SketchSetup | null): boolean {
  if (!needs.length) return true
  if (!setup) return false
  const shops = Object.values(setup.shops)
  const focus = setup.shops[setup.focus]
  return needs.every((need) => {
    if (need === 'price') return !!focus && Object.keys(focus.price).length > 0
    if (need === 'hours') return !!focus?.open && !!focus?.close
    if (need === 'rival') return shops.length > 1
    if (need.startsWith('product:')) {
      const p = need.slice('product:'.length)
      return shops.some((s) => s.products.some((x) => x.toLowerCase().includes(p)))
    }
    return false
  })
}

function score(s: RawSketch, f: Set<string>, lower: string, setup: SketchSetup | null): { r: number; hits: number } {
  const lever = LEVERS[s.lever]
  const [topic, ...details] = lever.tags
  const hits = details.filter((t) => hit(t, f, lower)).length
  let r = 0
  if (hits || hit(topic, f, lower)) r += W.topic
  r += W.detail * Math.min(hits, 3) / 3
  if (SEGMENTS[s.segment].some((t) => hit(t, f, lower))) r += W.audience
  if (setupSatisfied(lever.setup, setup)) r += W.setup
  return { r: Math.round(r * 100) / 100, hits }
}

function fill(s: RawSketch, setup: SketchSetup | null, rivalId: string | null): MockAnswer {
  const shop = setup?.shops[setup.focus]?.name ?? 'your shop'
  const rival = (rivalId && setup?.shops[rivalId]?.name)
    || (setup ? Object.entries(setup.shops).find(([id]) => id !== setup.focus)?.[1].name : undefined)
    || 'the shop across the street'
  const sub = (t: string) => t.replaceAll('{shop}', shop).replaceAll('{rival}', rival)
  return { headline: sub(s.headline), movements: s.movements.map(sub), drivers: s.drivers, net: sub(s.net) }
}

/** Score the whole pool against the plan and the set-up, shortlist the top 40, keep the ones at or
 *  above the 70% bar, and return the best one not shown yet this browser session. When the plan
 *  matches nothing the shortlist is random. */
export const pickMock = (text: string, setup: SketchSetup | null): Picked => {
  const lower = text.toLowerCase()
  const { f, rival } = features(text, setup)
  const scored = SKETCHES.map((s, i) => ({ i, ...score(s, f, lower, setup), tie: Math.random() }))
  scored.sort((a, b) => b.r - a.r || b.hits - a.hits || a.tie - b.tie)
  const top = scored.slice(0, SHORTLIST)
  const cleared = top.filter((x) => x.r >= RELEVANCE_BAR)
  const candidates = cleared.length ? cleared : top

  let used = seen()
  let fresh = candidates.filter((x) => !used.includes(x.i))
  if (!fresh.length) {
    const ids = new Set(candidates.map((x) => x.i))
    used = used.filter((i) => !ids.has(i))
    fresh = candidates
  }
  const best = fresh[0]
  remember([...used, best.i])
  return { mock: fill(SKETCHES[best.i], setup, rival), relevance: best.r, shortlisted: cleared.length, poolSize: POOL_SIZE }
}
